# Generated by Django 5.0.4 on 2024-04-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0002_saving_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='item_owner',
        ),
    ]
